name: Pull Request

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.m2/repository
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}

      - name: Prepare
        run: |
          touch local.properties
          echo "org.gradle.jvmargs=-Xmx4g" >> gradle.properties

      - name: Build MaterialThemeBuilder
        run: |
          git clone --depth=1 --recurse-submodules \
            https://github.com/LSPosed/MaterialThemeBuilder \
            -b agp9.0 ~/MaterialThemeBuilder

          cd ~/MaterialThemeBuilder
          chmod +x gradlew
          ./gradlew -x test publishToMavenLocal

      - name: Prebuild
        run: ./gradlew prebuild

      - name: Build Release
        run: |
          ./gradlew :app:assembleRelease
          ./gradlew :zygote:assembleRelease

      - name: Upload Release
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: |
            app/build/outputs/apk/release/*.apk
            zygote/build/outputs/magisk/release/*.zip
